<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /home/kahuna/buildkit/build/d519/web/sites/default/files/civicrm/ext/org.makerspacetoolkit.accessmanagement/xml/schema/CRM/Accessmanagement/GroupAcls.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:da5a3a2a0d47b266312dddc21a169165)
 */

/**
 * Database access object for the GroupAcls entity.
 */
class CRM_Accessmanagement_DAO_GroupAcls extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_mstk_group_acls';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique GroupAcls ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Group
   *
   * @var int
   */
  public $group_id;

  /**
   * FK to Access Points
   *
   * @var int
   */
  public $aco;

  /**
   * @var int
   */
  public $status_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_mstk_group_acls';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'group_id', 'civicrm_group', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'aco', 'civicrm_mstk_access_points', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Accessmanagement_ExtensionUtil::ts('Unique GroupAcls ID'),
          'required' => TRUE,
          'where' => 'civicrm_mstk_group_acls.id',
          'table_name' => 'civicrm_mstk_group_acls',
          'entity' => 'GroupAcls',
          'bao' => 'CRM_Accessmanagement_DAO_GroupAcls',
          'localizable' => 0,
        ],
        'group_id' => [
          'name' => 'group_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Accessmanagement_ExtensionUtil::ts('FK to Group'),
          'where' => 'civicrm_mstk_group_acls.group_id',
          'table_name' => 'civicrm_mstk_group_acls',
          'entity' => 'GroupAcls',
          'bao' => 'CRM_Accessmanagement_DAO_GroupAcls',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Group',
        ],
        'aco' => [
          'name' => 'aco',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Accessmanagement_ExtensionUtil::ts('Aco'),
          'description' => CRM_Accessmanagement_ExtensionUtil::ts('FK to Access Points'),
          'where' => 'civicrm_mstk_group_acls.aco',
          'table_name' => 'civicrm_mstk_group_acls',
          'entity' => 'GroupAcls',
          'bao' => 'CRM_Accessmanagement_DAO_GroupAcls',
          'localizable' => 0,
          'FKClassName' => 'CRM_Accessmanagement_DAO_AccessPoints',
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_INT,
          'required' => TRUE,
          'where' => 'civicrm_mstk_group_acls.status_id',
          'table_name' => 'civicrm_mstk_group_acls',
          'entity' => 'GroupAcls',
          'bao' => 'CRM_Accessmanagement_DAO_GroupAcls',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'mstk_group_acls', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'mstk_group_acls', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
